files:
  include: 'app/styles/**/*.scss'
  ignore: 'app/styles/_state.scss'
rules:
  border-zero: [2, convention: '0']
  class-name-format: 0
  clean-import-paths: 0
  empty-args: [2, include: true]
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  indentation: 0
  # waiting on https://github.com/sasstools/sass-lint/issues/70
  # to fix incorrectly reported indentation errors
  # indentation: [2, size: 2]
  leading-zero: 0
  mixins-before-declarations: 0
  nesting-depth: [2, max-depth: 4]
  no-color-literals: 0
  no-css-comments: 0
  no-empty-args: 0
  no-ids: 0
  no-important: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0
  no-warn: 0
  placeholder-in-extend: 0
  property-sort-order: [2, ignore-custom-properties: true]
  quotes: [2, style: 'single']
  shorthand-values: 0
  space-after-comma: [2, include: true]
  space-around-operator: 0
