language: node_js
node_js:
  - "0.10"
addons:
  firefox: "34.0"
env:
  global:
    - DISABLE_ROUTE_LOGGING=true

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@2.1
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - java -jar selenium-server-standalone-2.43.1.jar &> /dev/null &

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install the resources necessary for the auth server.
  - git clone git://github.com/mozilla/fxa-auth-server.git --depth 1
  - cd fxa-auth-server
  - npm install
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - cd ..
  - npm start &
  - sleep 20

# now run the tests!
script:
  - grunt validate-shrinkwrap --force # check for vulnerable modules via nodesecurity.io
  - grunt lint
  - travis_retry npm run test-travis
  - travis_retry npm run test-server
