language: node_js
node_js:
  - "0.10"
addons:
  firefox: "38.0.1"
  apt_packages:
    - libgmp-dev
env:
  global:
    - DISABLE_ROUTE_LOGGING=true

sudo: false

cache:
  directories:
    - node_modules
    - app/bower_components
    - fxa-auth-server/node_modules

before_install:
  # Update npm to 2.4
  - npm install -g npm@2.4
  # Setup the xvfb environment. Read more at http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar &> /dev/null &

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install --silent
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install the resources necessary for the auth server.
  - mkdir -p fxa-auth-server
  - cd fxa-auth-server && git init && git pull git://github.com/mozilla/fxa-auth-server.git --depth 1
  # first npm install will fail because there is no global GMP, we add localGmp after that failure
  - npm install
  # start the DB server
  - cd node_modules/fxa-auth-db-mem
  - LOG_LEVEL=error npm start &
  - cd ../../
  # start the auth server
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - cd ..
  - npm start &
  - sleep 5

# now run the tests!
script:
  - grunt validate-shrinkwrap --force # check for vulnerable modules via nodesecurity.io
  - grunt lint
  - travis_retry npm run test-travis
  - travis_retry npm run test-server
