language: node_js
node_js:
  - "0.10"
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: fxa-content
    - SAUCE_ACCESS_KEY: ee5354a4-3d5e-47a0-84b0-0b7aaa12a720

before_install:
  - sudo apt-get install libgmp3-dev

install:
# install everything for full dev in the fxa-content-server.
  - npm install --silent
# install the resources necessary for the auth server.
  - cd node_modules/fxa-auth-server
  - npm install --silent
  - node ./scripts/gen_keys.js
  - npm start &
  - cd ../..
# copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  - grunt po2json
# build task will perform lint
  - grunt build:travis
  - grunt serverproc:dist &
# now run the tests!
script: npm run-script test-server && npm run-script test-remote
