language: node_js
node_js:
  - "0.10"
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: fxa-content
    - SAUCE_ACCESS_KEY: ee5354a4-3d5e-47a0-84b0-0b7aaa12a720
    - DISABLE_ROUTE_LOGGING: true

before_install:
  - sudo apt-get install libgmp3-dev

install:
# install everything for full dev in the fxa-content-server.
# NPM install uses a custom mirror via https://github.com/jbuck/npm-readonly-mirror
  - npm install --silent --registry https://dccmzgc64kzf2.cloudfront.net/
# copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  - grunt l10n-create-json
# install the resources necessary for the auth server.
  - npm install --silent git://github.com/mozilla/fxa-auth-server.git --registry https://dccmzgc64kzf2.cloudfront.net/
  - cd node_modules/fxa-auth-server
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - cd ../..
  - npm start &
# now run the tests!
script: grunt validate-shrinkwrap && grunt lint && npm run-script test-server && npm run-script test-remote
